spring:
    datasource:
        name: dclog
        url: jdbc:oracle:thin:@localhost:1521:xe
        username: dclog
        password: dc2015
        # HikariDataSource
        type: com.zaxxer.hikari.HikariDataSource
#        driver-class-name: oracle.jdbc.driver.OracleDriver
        hikari:
          idle-timeout: 600000
          maximum-pool-size: 5
          minimum-idle: 2
          connection-test-query: SELECT 'x' FROM DUAL
          pool-name: dcPol
          max-lifetime: 1800000
          connection-timeout: 30000
          driver-class-name: oracle.jdbc.driver.OracleDriver
#        filters: stat
#        maxActive: 5
#        initialSize: 0
#        maxWait: 60000
#        minIdle: 1
#        timeBetweenEvictionRunsMillis: 60000
#        minEvictableIdleTimeMillis: 300000
#        validationQuery: SELECT 'x' FROM DUAL
#        testWhileIdle: true
#        testOnBorrow: false
#        testOnReturn: false
#        poolPreparedStatements: true
#        maxOpenPreparedStatements: 20
    aop:
      auto: true
    thymeleaf:
    cache: false